public enum TokenNames {

  MINUS, DIVIDE, NUMBER, EOF, PLUS,
  ID, STRING, error, SEMICOLON, RPAREN,
  TIMES, LPAREN, ASSIGN, EQ, LBRACK, LT,
  RBRACK, GT, LBRACE, RBRACE, COMMA, DOT,
  ARRAY, CLASS, EXTENDS, NIL, WHILE, RETURN, IF, NEW


}

